export const LANG_AR_NAME = 'ar';

export const LANG_AR_TRANS = {
  'Accueil': 'الصفحة الرئيسية',
  'Sauvegarder': 'حفظ',
  'Langue':'اللغة',
  'Paramètres':'إعدادات',
  'Paiement Direct':'الدفع المباشر',
  'Accès Client':'بوابة الزبون',
  'Paiement':'الدفع',
  'Valider':'تاكيد',
  'Numéro de contrat':'رقم العقد',
  'Mot de passe':'كلمة السر',
  'Identifiant':'الدخول',
  'Mémoriser':'حفظ',
  'Mot de passe oublié?':'نسيت كلمة المرور',
  'Créer Compte':'إنشاء حساب',
  'actu':'أخبار',
  'reso':'شبكة',
  'home':'الرئيسية',
  'params':'إعدادات',
  'contact':'اتصال',
  'PassReset':'نسيت كلمة المرور؟',
  'Email':'البريد الالكتروني',
  'pay':'دفع فواتيري على فاتورتي',
  "signout": "خروج",
  "home_msg_1":"لتسديد فواتيرك ، انقر ببساطة على الزر - قم بسداد فواتيري على"+
  "فاتورتي - وستتم إعادة توجيهك إلى صفحة الدفع",
  "Mes Factures":"فواتيري",
  "Echéance":"استحقاقات",
  "Historique consommation":"تاريخ الاستهلاك",
  "Réclamations":"الشكاوى",
  "Devis":"التسعير",
  "Simulation":"محاكاة",
  "Domiciliation Bancaire":"التسوية المصرفية",
  "Demande d'abonnement": "طلب الاشتراك",
  "Inscription":"تسجيل",
  "News":"أخبار",
  "Videos":"فيديو",
  "Agences":"وكالات",
  "Espaces services":"مساحات الخدمات",
  "Gab":"جهاز الصراف الآلي",
};