export const LANG_FR_NAME = 'fr';

export const LANG_FR_TRANS = {
  'Accueil': 'Accueil',
  'Sauvegarder': 'Sauvegarder',
  'Langue':'Langue',
  'Paramètres':'Paramètres',
  'Paiement Direct':'Paiement Direct',
  'Accès Client':'Accès Client',
  'Paiement':'Paiement',
  'Valider':'Validate',
  'Numéro de contrat':'Numéro de contrat',
  'Mot de passe':'Mot de passe',
  'Identifiant':'Identifiant',
  'Mémoriser':'Mémoriser',
  'Mot de passe oublié?':'Mot de passe oublié',
  'Créer Compte':'Créer Compte',
  'actu':'Actualités',
  'reso':'Réseau',
  'home':'Accueil',
  'params':'Paramètres',
  'contact':'Contact',
  'PassReset':'Mot de passe oublié?',
  'Email':'Adresse e-mail',
  'signout': 'Déconnecter',
  'pay':'Payer mes factures sur Fatourati',
  "home_msg_1":"Pour payer vos factures, il vous suffit de cliquer sur le bouton"+
   "-Payer mes factures sur Fatourati- et vous serez redirigé vers la page de paiement.",
  "Mes Factures":"Mes Factures",
  "Echéance":"Echéance",
  "Historique consommation":"Historique consommation",
  "Réclamations":"Réclamations",
  "Devis":"Devis",
  "Simulation":"Simulation",
  "Domiciliation Bancaire":"Domiciliation Bancaire",
  "Demande d'abonnement": "Demande d'abonnement",
  "Inscription":"Inscription",
  "News":"Nouvelles",
  "Videos":"Vidéos",
  "Agences":"Agences",
  "Espaces services":"Espaces services",
  "Gab":"Gab",
};