export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'Accueil': 'Home',
  'Sauvegarder': 'Save',
  'Langue':'Language',
  'Paramètres':'Settings',
  'Paiement Direct':'Direct Payment',
  'Accès Client':'Customer Access',
  'Paiement':'Payment',
  'valider':'Validate',
  'Numéro de contrat':'Contract number',
  'password':'Password',
  'identifiant':'ID Card or passport ',
  'Mémoriser':'To memorize',
  'Mot de passe oublié?':'Forgot your password?',
  'Créer Compte':'Create account',
  'actu':'News',
  'reso':'Network',
  'home':'Home',
  'params':'Settings',
  'contact':'Contact',
  'PassReset':'Forgot your password?',
  'email':'e-mail adress',
  'signout': 'Sign Out',
  'pay':'Pay my bills on Fatourati',
  "home_msg_1":"To pay your bills, simply click on the button"+
    "-Pay my bills on Fatourati- and you will be redirected to the payment page.",
  "Mes Factures":"My bills",
  "Echéance":"Maturities",
  "Historique consommation":"Consumption History",
  "Réclamations":"Complaints",
  "Devis":"Quotation",
  "Simulation":"Simulation",
  "Domiciliation Bancaire":"Banking Domiciliation",
  "Demande d'abonnement": "Subscription request",
  "inscription":"Registration",
  "News":"News",
  "Videos":"Videos",
  "Agences":"Agencies",
  "Espaces services":"Service areas",
  "Gab":"ATM Machines",
  "AssocierContrat":"Associate my contracts",
  "register_msg":"Welcome to your online agency. Please enter the necessary "+
    "informations to create your account",
  "etape1":"Step 1",
  "etape2":"Step 2",
  "titre":"Title",
  "prenom":"First Name",
  "nom":"Last Name",
  "suivant":"Next",
  "tel":"Cellphone",
  "conditions":"Terms of Service",
  "precedent":"Previous",
  "reset_msg":"To recover your account, enter your email address.",
  "mr":"Mr",
  "mme":"Mrs",
  "mlle":"Ms",
  "MesContrats":"My contracts",
};