export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'Accueil': 'Home',
  'Sauvegarder': 'Save',
  'Langue':'Language',
  'Paramètres':'Settings',
  'Paiement Direct':'Direct Payment',
  'Accès Client':'Customer Access',
  'Paiement':'Payment',
  'Valider':'Validate',
  'Numéro de contrat':'Contract number',
  'Mot de passe':'Password',
  'Identifiant':'Login',
  'Mémoriser':'To memorize',
  'Mot de passe oublié?':'Forgot your password',
  'Créer Compte':'Create account',
  'actu':'News',
  'reso':'Network',
  'home':'Home',
  'params':'Settings',
  'contact':'Contact',
  'PassReset':'Forgot your password?',
  'Email':'e-mail adress',
  'signout': 'Sign Out',
  'pay':'Pay my bills on Fatourati',
  "home_msg_1":"To pay your bills, simply click on the button"+
    "-Pay my bills on Fatourati- and you will be redirected to the payment page.",
  "Mes Factures":"My bills",
  "Echéance":"Maturities",
  "Historique consommation":"Consumption History",
  "Réclamations":"Complaints",
  "Devis":"Quotation",
  "Simulation":"Simulation",
  "Domiciliation Bancaire":"Banking Domiciliation",
  "Demande d'abonnement": "Subscription request",
  "Inscription":"Registration",
  "News":"News",
  "Videos":"Videos",
  "Agences":"Agencies",
  "Espaces services":"Service areas",
  "Gab":"ATM Machines",
};