export const LANG_AR_NAME = 'ar';

export const LANG_AR_TRANS = {
  'Accueil': 'الصفحة الرئيسية',
  'Sauvegarder': 'حفظ',
  'Langue':'اللغة',
  'Paramètres':'إعدادات',
  'Paiement Direct':'الدفع المباشر',
  'Accès Client':'بوابة الزبون',
  'Paiement':'الدفع',
  'valider':'تاكيد',
  'Numéro de contrat':'رقم العقد',
  'password':'كلمة السر',
  'identifiant':'رقم بطاقة التعريف الوطنية أو جواز سفر',
  'Mémoriser':'حفظ',
  'Mot de passe oublié?':'نسيت كلمة المرور',
  'Créer Compte':'إنشاء حساب',
  'actu':'أخبار',
  'reso':'شبكة',
  'home':'الرئيسية',
  'params':'إعدادات',
  'contact':'اتصال',
  'PassReset':'نسيت كلمة المرور؟',
  'email':'البريد الالكتروني',
  'pay':'دفع فواتيري على فاتورتي',
  "signout": "خروج",
  "home_msg_1":"لتسديد فواتيرك ، انقر ببساطة على الزر - قم بسداد فواتيري على"+
  "فاتورتي - وستتم إعادة توجيهك إلى صفحة الدفع",
  "Mes Factures":"فواتيري",
  "Echéance":"استحقاقات",
  "Historique consommation":"تاريخ الاستهلاك",
  "Réclamations":"الشكاوى",
  "Devis":"التسعير",
  "Simulation":"محاكاة",
  "Domiciliation Bancaire":"التسوية المصرفية",
  "Demande d'abonnement": "طلب الاشتراك",
  "inscription":"تسجيل",
  "News":"أخبار",
  "Videos":"فيديو",
  "Agences":"وكالات",
  "Espaces services":"مساحات الخدمات",
  "Gab":"جهاز الصراف الآلي",
  "AssocierContrat":"اربط عقدي",
  "register_msg":"مرحبا بكم . يرجى إدخال المعلومات اللازمة لإنشاء حسابك",
  "etape1":"المرحلة 1",
  "etape2":"المرحلة 2",
  "titre":"لقب",
  "prenom":"الاسم الشخصي",
  "nom":"الاسم العائلي",
  "suivant":"التالي",
  "tel":"هاتف محمول",
  "conditions":"شروط الخدمة",
  "precedent":"السابق",
  "reset_msg":"لاستعادة حسابك ، أدخل عنوان بريدك الإلكتروني",
  "mr":"السيد",
  "mme":"السيدة",
  "mlle":"الآنسة",
  "MesContrats":"عقودي",
};