export const LANG_FR_NAME = "fr";

export const LANG_FR_TRANS = {
  "menu":"Menu",
  "espace_cli":"Espace Client",
  "cta_type":"Type contrat",
  "sauvegarder": "Sauvegarder",
  "langue":"Langue",
  "direct_pay":"Paiement Direct",
  "access_cli":"Accès Client",
  "valider":"Valider",
  "num_cta":"Numéro de contrat",
  "password":"Mot de passe",
  "identifiant":"Cin ou Passeport",
  "memoriser":"Mémoriser",
  "Mot de passe oublié?":"Mot de passe oublié",
  "creer_comp":"Créer Compte",
  "welcome":"Bienvenue",
  "home":"Accueil",
  "actu":"Actualités",
  "paiement":"Paiement",
  "reso":"Réseau",
  "params":"Paramètres",
  "contact":"Contact",
  "associerContrat":"Associer mes contrats",
  "mesContrats":"Mes contrats",
  "mesFactures":"Mes Factures",
  "eFacture":"E-Facture",
  "echeances":"Echéances",
  "maConso":"Ma consommation",
  "reclamations":"Réclamations",
  "devis":"Devis",
  "simulation":"Simulation",
  "domiciliation":"Domiciliation Bancaire",
  "abonnement": "Demande d'abonnement",
  "inscription":"Inscription",
  "news":"Nouvelles",
  "videos":"Vidéos",
  "agences":"Agences",
  "Agence":"Agence",
  "tasshilat":"Tasshilat",
  "fawatir":"Fawatir",
  "espaces":"Espaces services",
  "gab":"Gab",
  "Gab":"Gab",
  "PassReset":"Mot de passe oublié?",
  "email":"Adresse e-mail",
  "signout": "Déconnecter",
  "pay":"Payer mes factures sur Fatourati",
  "etape1":"Etape 1",
  "etape2":"Etape 2",
  "etape3":"Etape 3",
  "etape4":"Etape 4",
  "titre":"Titre",
  "prenom":"Prénom",
  "nom":"Nom",
  "suivant":"Suivant",
  "tel":"Téléphone portable",
  "conditions":"Conditions générales d'utilisation",
  "precedent":"Précédent",
  "mr":"Mr",
  "mme":"Mme",
  "mlle":"Mlle",
  "eFacture_msg":"<ul>La facture électronique (e-Facture) est un moyen rapide, facile, sécurisé et GRATUIT d'éliminer votre facture papier et de recevoir et de payer votre facture en ligne : "+
    "<li>Recevez automatiquement votre facture par e-mail</li>"+
    "<li>Recevez une notification par e-mail lorsque votre facture est exigible</li>"+
    "<li>Consulter votre facture en ligne</li>"+
    "<li>Votre facture en ligne est identique à votre facture papier et est disponible pour consultation, téléchargement ou impression à tout moment.</li></ul>",
  "home_msg_1":"Pour payer vos factures, il vous suffit de cliquer sur le bouton"+
    "-Payer mes factures sur Fatourati- et vous serez redirigé vers la page de paiement.",
  "register_msg":"Bienvenue dans votre agence en ligne. Veuillez saisir les "+
    "informations nécessaire pour pouvoir créer votre compte",
  "reset_msg":"Pour récupérer votre compte, saisissez votre adresse e-mail.",
  "no_cta_msg":"Vous n'avez pas encore de contrat",
  "no_facture_msg":"Vous n'avez pas de factures!",
  "no_facture":"Numéro de facture",
  "facture_color":"Les factures marquées en rose sont des factures impayées",
  "type_facture":"Type de facture",
  "period":"Période",
  "montant":"Montant",
  "solde":"Solde",
  "exigibilite":"Date d'exigibilité",
  "montant_reg":"Montant réglé",
  "type_reg":"Type réglement",
  "mode_reg":"Mode de réglement",
  "date_reg":"Date de réglement",
  "no_result":"Pas de résultat pour ce contrat.",
  "index":"Index",
  "date_rel":"Date de la relève",
  "type_rel":"Type relève",
  "nbr_jr":"Nombre de jours",
  "vol_cons":"Volume consommé",
  "vol_fac":"Volume facturé",
  "detail_fact":"Détails facture",
  "visualiser":"Visualiser mon historique",
  "fermer":"Fermer",
  "barre":"Barre",
  "courbe":"Courbe",
  "export_pdf":"Exporter PDF",
  "add_recl":"Soumettre réclamation",
  "no_recl":"N° Réclamation",
  "date_recl":"Date Réclamation",
  "etat_recl":"Etat Réclamation",
  "type_recl":"Type Réclamation",
  "msg_recl":"Votre message",
  "tel_recl":"Téléphone de contact",
  "choose_cta":"Choisir votre contrat",
  "choose_origin":"Choisir origine",
  "choose_type":"Choisir Type",
  "envoyer":"Envoyer",
  "commentaire":"Commentaire",
  "tourne":"Tournée",
  "service":"Service",
  "id_type":"Type pièce d'identité",
  "num_id":"Numéro pièce",
  "adress":"Adresse",
  "usage_elec":"Usage Electricité ",
  "usage_eau":"Usage Eau ",
  "iam":"Je suis un ?",
  "proprietaire":"Propriétaire",
  "locataire":"Locataire",
  "jerepresente":"Je représente une ?",
  "personne":"Personne physique",
  "societe":"Société",
  "confirmation":"Confirmation :",
  "soumettre":"Soumettre",
  "ajouter":"Ajouter",
  "accepter":"Accepter",
  "contact_message":"Le Centre de Relation Clientèle RADEEMA est à votre disposition"+
    " 24h/24 et 7j/7. <br> Vos comentaires, suggestions et réclamations sont les bienvenus.",
  "nom_prenom":"Nom & Prénom",
  "object":"Objet",
  "details":"Détails",
  "complete_name":"Je soussigné (nom complet)",
  "cin":"Pièce d'identité",
  "adress_dom":"Adresse de correspondance",
  "bank_name":"Nom de la banque",
  "agence" :"Votre Agence",
  "code_bank":"Code banque",
  "localite":"Code localité",
  "ref_compte":"Référence de compte",
  "cle":"Clé",
  "accept_dom":"Je demande à la RADEEMA de procéder au réglement de mes factures d'Eau et d'Electricité par prélevement bancaire.",
  "obligatoire":"Obligatoire",
  "accepter_notif":"Accepter de recevoir de la RADEEMA des notifications par e-mail",
  "abonner":"S'abonner",
  "num_faci":"N° facilité",
  "etat_faci":"Etat facilité",
  "mnt_faci":"Montant facilité",
  "echeance_detail":"Détails Echéance",
  "ordre_ech":"Ordre Echéance",
  "mnt_ech":"Montant Echéance",
  "date_ech":"Date Echéance",
  "etat_ech":"Etat Echéance",
  "mon_compte":"Mon compte client",
  "num_client":"N° Client",
  "nom_client":"Client",
  "impayes":"Montant impayés",
  "mt_exigible":"Montant exigible",
  "credit":"Crédit sur mon compte",
  "provision":"Provision",
};