export const LANG_FR_NAME = 'fr';

export const LANG_FR_TRANS = {
  'Accueil': 'Accueil',
  'Sauvegarder': 'Sauvegarder',
  'Langue':'Langue',
  'Paramètres':'Paramètres',
  'Paiement Direct':'Paiement Direct',
  'Accès Client':'Accès Client',
  'Paiement':'Paiement',
  'valider':'Valider',
  'Numéro de contrat':'Numéro de contrat',
  'password':'Mot de passe',
  'identifiant':'Cin ou Passeport',
  'Mémoriser':'Mémoriser',
  'Mot de passe oublié?':'Mot de passe oublié',
  'Créer Compte':'Créer Compte',
  'actu':'Actualités',
  'reso':'Réseau',
  'home':'Accueil',
  'params':'Paramètres',
  'contact':'Contact',
  'PassReset':'Mot de passe oublié?',
  'email':'Adresse e-mail',
  'signout': 'Déconnecter',
  'pay':'Payer mes factures sur Fatourati',
  "home_msg_1":"Pour payer vos factures, il vous suffit de cliquer sur le bouton"+
    "-Payer mes factures sur Fatourati- et vous serez redirigé vers la page de paiement.",
  "Mes Factures":"Mes Factures",
  "Echéance":"Echéance",
  "Historique consommation":"Historique consommation",
  "Réclamations":"Réclamations",
  "Devis":"Devis",
  "Simulation":"Simulation",
  "Domiciliation Bancaire":"Domiciliation Bancaire",
  "Demande d'abonnement": "Demande d'abonnement",
  "inscription":"Inscription",
  "News":"Nouvelles",
  "Videos":"Vidéos",
  "Agences":"Agences",
  "Espaces services":"Espaces services",
  "Gab":"Gab",
  "AssocierContrat":"Associer mes contrats",
  "register_msg":"Bienvenue dans votre agence en ligne. Veuillez saisir les "+
    "informations nécessaire pour pouvoir créer votre compte",
  "etape1":"Etape 1",
  "etape2":"Etape 2",
  "titre":"Titre",
  "prenom":"Prénom",
  "nom":"Nom",
  "suivant":"Suivant",
  "tel":"Téléphone portable",
  "conditions":"Conditions générales d'utilisation",
  "precedent":"Précédent",
  "reset_msg":"Pour récupérer votre compte, saisissez votre adresse e-mail.",
  "mr":"Mr",
  "mme":"Mme",
  "mlle":"Mlle",
  "MesContrats":"Mes contrats",
};