export const LANG_EN_NAME = "en";

export const LANG_EN_TRANS = {
  "menu":"Menu",
  "espace_cli":"Customer Area",
  "cta_type":"Contract type",
  "sauvegarder": "Save",
  "langue":"Language",
  "direct_pay":"Direct Payment",
  "access_cli":"Customer Access",
  "valider":"Validate",
  "num_cta":"Contract number",
  "password":"Password",
  "identifiant":"ID Card or passport ",
  "memoriser":"To memorize",
  "Mot de passe oublié?":"Forgot your password?",
  "creer_comp":"Create account",
  "welcome":"Welcome",
  "home":"Home",
  "actu":"News",
  "reso":"Network",
  "paiement":"Payment",
  "params":"Settings",
  "contact":"Contact",
  "associerContrat":"Associate my contracts",
  "mesContrats":"My contracts",
  "mesFactures":"My bills",
  "eFacture":"E-Invoice",
  "echeances":"Maturities",
  "maConso":"My consumption",
  "reclamations":"Complaints",
  "devis":"Quotation",
  "simulation":"Simulation",
  "domiciliation":"Banking Domiciliation",
  "abonnement": "Subscription request",
  "inscription":"Registration",
  "news":"News",
  "videos":"Videos",
  "agences":"Agencies",
  "Agence":"Agency",
  "tasshilat":"Tasshilat",
  "fawatir":"Fawatir",
  "espaces":"Service areas",
  "gab":"ATM Machines",
  "Gab":"ATM Machines",
  "email":"E-mail address",
  "signout": "Sign Out",
  "pay":"Pay my bills on Fatourati",
  "PassReset":"Forgot your password?",
  "etape1":"Step 1",
  "etape2":"Step 2",
  "etape3":"Step 3",
  "etape4":"Step 4",
  "titre":"Title",
  "prenom":"First Name",
  "nom":"Last Name",
  "suivant":"Next",
  "tel":"Cellphone",
  "conditions":"Terms of Service",
  "precedent":"Previous",
  "mr":"Mr",
  "mme":"Mrs",
  "mlle":"Ms",
  "home_msg_1":"To pay your bills, simply click on the button"+
    "-Pay my bills on Fatourati- and you will be redirected to the payment page.",
  "register_msg":"Welcome to your online agency. Please enter the necessary "+
    "informations to create your account",
  "reset_msg":"To recover your account, enter your email address.",
  "eFacture_msg":"<ul>The e-Invoice is a fast, easy, secure and FREE way to eliminate your paper bill and receive and pay your bill online:"+
  "<li>Automatically receive your invoice by e-mail</li>"+
  "<li>Receive an e-mail notification when your bill is due</li>"+
  "<li>View your invoice online</li>"+
  "<li>Your online invoice is identical to your paper invoice and is available for consultation, download or printing at any time.</li></ul>",
  "no_cta_msg":"You do not have a contract yet",
  "no_facture_msg":"You don't have invoices!",
  "facture_color":"Invoices marked in pink are unpaid invoices",
  "no_facture":"Invoice number",
  "type_facture":"Invoice type",
  "period":"Period",
  "montant":"Amount",
  "solde":"Balance",
  "exigibilite":"Due date",
  "montant_reg":"Amount rule",
  "type_reg":"Settlement type",
  "mode_reg":"Payment choice",
  "date_reg":"Settlement date",
  "no_result":"No result for this contract.",
  "index":"Index",
  "date_rel":"Date of reading",
  "type_rel":"Type of reading",
  "nbr_jr":"Number of days",
  "vol_cons":"Consumed volume",
  "vol_fac":"Billed volume",
  "detail_fact":"Bill details",
  "visualiser":"View my history",
  "fermer":"Close",
  "barre":"Bar",
  "courbe":"Line",
  "export_pdf":"Export PDF",
  "add_recl":"Submit complaint",
  "no_recl":"Complaint number",
  "date_recl":"Complaint date",
  "etat_recl":"Complaint state",
  "type_recl":"Complaint type",
  "msg_recl":"Your message",
  "tel_recl":"Contact phone",
  "choose_cta":"Choose your contract",
  "choose_origin":"Choose origin",
  "choose_type":"Choose type",
  "envoyer":"Send",
  "commentaire":"Comment",
  "tourne":"Tour",
  "service":"Service",
  "id_type":"ID type",
  "num_id":"ID number",
  "adress":"Address",
  "usage_elec":"Electricity use",
  "usage_eau":"Water use",
  "iam":"I am a ?",
  "proprietaire":"Owner",
  "locataire":"Tenant",
  "jerepresente":"I represent a",
  "personne":"Physical person",
  "societe":"Society",
  "confirmation":"Confirmation :",
  "soumettre":"Submit",
  "ajouter":"Add",
  "accepter":"Accept",
  "contact_message":"The Customer Relations Center RADEEMA is at your disposal 24 hours"+
    " a day, 7 days a week. <br> Your comments, suggestions and complaints are welcome.",
  "nom_prenom":"First name & Last name",
  "object":"Object",
  "details":"Details",
  "complete_name":"I, the undersigned (full name)",
  "cin":"ID",
  "adress_dom":"Mailing address",
  "bank_name":"Bank name",
  "agence" :"Your Agency",
  "code_bank":"Bank code",
  "localite":"Location code",
  "ref_compte":"Account reference",
  "cle":"Key",
  "accept_dom":"I ask RADEEMA to proceed with the payment of my water and electricity bills by bank levy.",
  "obligatoire":"Mandatory",
  "accepter_notif":"Accept to receive notifications from RADEEMA by e-mail",
  "abonner":"Subscribe",
  "num_faci":"No. facility",
  "etat_faci":"Facility state",
  "mnt_faci":"Facility amount",
  "echeance_detail":"Maturity details",
  "ordre_ech":"Maturity order",
  "mnt_ech":"Maturity amount",
  "date_ech":"Maturity date",
  "etat_ech":"Maturity state",
  "mon_compte":"My account",
  "num_client":"No. client",
  "nom_client":"Client",
  "impayes":"Unpaid amount",
  "mt_exigible":"Due amount",
  "credit":"Credit on my account",
  "provision":"Provision",
};